### ISSUE TITLE
That's not working in Android Studio 4.1

### ISSUE THREAD

**Issue by lmint1** [ktvipin27/ArchitectureTemplate#1]
It's working well in android studio 4.0. Do you have any thought about this?

**Comment by ktvipin27** [comment]
Android Studio 4.1 uses a new templating API which is visible but not public yet, Unfortunately in the process, Google seem to have removed the old way of adding templates.
If you are interested in tracking progress, you can star the issue on Google's issue tracker system [here](https://issuetracker.google.com/issues/154531807).

Also the locations of user configuration directories have been changed 
[https://developer.android.com/studio/releases#directory-configuration-changes](https://developer.android.com/studio/releases#directory-configuration-changes)
